#!/data/data/com.termux/files/usr/bin/bash
sleep 0.8

c1='\e[0;1;38;2;0;170;80m'
c2='\e[0;1;96m'

echo -e "\n\n${c1}       .hddddddddddddddddddddddh.
      :dddddddddddddddddddddddddd:
     /dddddddddddddddddddddddddddd/
    +dddddddddddddddddddddddddddddd+
   sdddddddddddddddddddddddddddddddds
  ydddddddddddd++hdddddddddddddddddddy
.hddddddddddd+    +ddddh:-sdddddddddddh.
hdddddddddd+        +y:    .sddddddddddh
ddddddddh+     //     .      -sddddddddd
ddddddh+     /hddh/     :s-    -sddddddd
ddddh+     /+/dddddh/     +s-    -sddddd
ddd+     /o  :dddddddh/     oy-    .yddd
hdddyo+ohddyosdddddddddho+oydddy++ohdddh
.hddddddddddddddddddddddddddddddddddddh.
  yddddddddddddddddddddddddddddddddddy
   sdddddddddddddddddddddddddddddddds
    +dddddddddddddddddddddddddddddd+
     /dddddddddddddddddddddddddddd/
      :dddddddddddddddddddddddddd:
       .hddddddddddddddddddddddh."

echo -e "\e[0;1m
  ____  _      ____  ____  ____     ___
 /    T| T    |    \l    j|    \   /  _]
Y  o  || |    |  o  )|  T |  _  Y /  [_
|     || l___ |   _/ |  | |  |  |Y    _]
|  _  ||     T|  |   |  | |  |  ||   [_
|  |  ||     ||  |   j  l |  |  ||     T
l__j__jl_____jl__j  |____jl__j__jl_____j"

echo
echo -ne "${c1}Are you want to continue installing (Y/N)? "
read input
if [[ $input = "Y" ]] || [[ $input = "y" ]]
then connection="$(ping -c 1 -q www.google.com >&/dev/null; echo $?)"
if [[ "$connection" != 0 ]]
then
echo -e "\033[1;91m          [\033[1;92m-\033[1;91m] No Internet\033[1;92m connection!"
echo
   exit
fi
sleep 1.5
cd $HOME
mkdir alpine > /dev/null 2>&1
cd alpine
echo
echo -e '\033[1m\033[38;2;0;80;255m[^_^] Alpine Installing Starting...'
sleep 1
echo
pkg update -y && pkg install wget curl proot tar -y && wget https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/Installer/Alpine/alpinexfce.sh && chmod +x alpinexfce.sh && bash alpinexfce.sh
elif [[ $input = "N" ]] || [[ $input = "n" ]]
then echo -e '\033[0m\033[1mAbort.'
echo
exit
fi
