#!/data/data/com.termux/files/usr/bin/bash
sleep 0.8
echo -e "\e[1m\e[38;2;0;60;255m
..............
            ..,;:ccc,.
          ......''';lxO.
.....''''..........,:ld;
           .';;;:::;,,.x,
      ..'''.            0Xxoc:,.  ...
  ....                ,ONkc;,;cokOdc',.
 .                   OMo           ':\e[38;2;255;0;100mdd\e[38;2;0;60;255mo.
                    dMc               :OO;
                    0M.                 .:o.
                    ;Wd
                     ;XO,
                       ,d0Odlc;,..
                           ..',;:cdOOd::,.
                                    .:d;.':;.
                                       'd,  .'
                                         ;l   ..
                                          .o
                                            c
                                            .'
                                             ."'\e[1;97m
                88  dP    db    88     88
                88odP    dPYb   88     88
                88"Yb   dP__Yb  88  .o 88
                88  Yb dP""""Yb 88ood8 88'
echo
echo
echo -n "Are you want to continue installing (Y/N)? "
read input
if [[ $input = "Y" ]] || [[ $input = "y" ]]
then connection="$(ping -c 1 -q www.google.com >&/dev/null; echo $?)"
if [[ "$connection" != 0 ]]
then
echo -e "\033[1;91m           [\033[1;92m-\033[1;91m] No Internet\033[1;92m connection!"
echo
   exit
fi
sleep 2.0
cd $HOME
echo
echo -e '\033[1m\033[38;2;0;80;255m[^_^] Installing Kali Linux...'
sleep 2.0
echo
apt update && apt install wget -y && wget -O install-nethunter-termux https://offs.ec/2MceZWr && chmod + install-nethunter-termux && bash install-nethunter-termux
elif [[ $input = "N" ]] || [[ $input = "n" ]]
then echo -e '\033[0m\033[1mAbort.'
echo
exit
fi
