#!/data/data/com.termux/files/usr/bin/bash
sleep 0.8
#colors
c2="\e[0m\e[1m"
c1="\e[1m\e[38;2;255;80;0m"

echo
echo -e "$c1                 .-/+oossssoo+/-.
              :+ssssssssssssssssss+:
           -+ssssssssssssssssssyyssss+-
         .ossssssssssssssssss${c2}dMMMNy${c1}sssso.
        /sssssssssss${c2}hdmmNNmmyNMMMMh${c1}ssssss/
       +sssssssss${c2}hm${c1}yd${c2}MMMMMMMNddddy${c1}ssssssss+
      /ssssssss${c2}hNMMM${c1}yh${c2}hyyyyhmNMMMNh${c1}ssssssss/
     .ssssssss${c2}dMMMNh${c1}ssssssssss${c2}hNMMMd${c1}ssssssss.
     +ssss${c2}hhhyNMMNy${c1}ssssssssssss${c2}yNMMMy${c1}sssssss+
     oss${c2}yNMMMNyMMh${c1}ssssssssssssss${c2}hmmmh${c1}ssssssso
     oss${c2}yNMMMNyMMh${c1}sssssssssssssshmmmh${c1}ssssssso
     +ssss${c2}hhhyNMMNy${c1}ssssssssssss${c2}yNMMMy${c1}sssssss+
     .ssssssss${c2}dMMMNh${c1}ssssssssss${c2}hNMMMd${c1}ssssssss.
      /ssssssss${c2}hNMMM${c1}yh${c2}hyyyyhdNMMMNh${c1}ssssssss/
       +sssssssss${c2}dm${c1}yd${c2}MMMMMMMMddddy${c1}ssssssss+
        /sssssssssss${c2}hdmNNNNmyNMMMMh${c1}ssssss/
         .ossssssssssssssssss${c2}dMMMNy${c1}sssso.
           -+sssssssssssssssss${c2}yyy${c1}ssss+-
              :+ssssssssssssssssss+:
                 .-/+oossssoo+/-."

echo '
  U)    uu b)                        t)
  U)    uu b)                      t)tTTT
  U)    uu b)BBBB  u)   UU n)NNNN    t)   u)   UU
  U)    uu b)   BB u)   UU n)   NN   t)   u)   UU
  U)    uu b)   BB u)   UU n)   NN   t)   u)   UU
   U)uuuu  b)BBBB   u)UUU  n)   NN   t)T   u)UUU'
echo
echo
echo -n "Are you want to continue installing (Y/N)? "
read input
if [[ $input = "Y" ]] || [[ $input = "y" ]]
then connection="$(ping -c 1 -q www.google.com >&/dev/null; echo $?)"
if [[ "$connection" != 0 ]]
then
echo -e "\033[1;91m          [\033[1;92m-\033[1;91m] No Internet\033[1;92m connection!"
echo
   exit
fi
sleep 1.5
cd $HOME
mkdir ubuntu > /dev/null 2>&1
cd ubuntu
echo
echo -e '\033[1m\033[38;2;0;80;255m[^_^] Ubuntu Installing Starting...'
sleep 1
echo
pkg update -y && pkg install wget curl proot tar -y && wget https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/Installer/Ubuntu19/ubuntu19-xfce.sh && chmod +x ubuntu19-xfce.sh && bash ubuntu19-xfce.sh
elif [[ $input = "N" ]] || [[ $input = "n" ]]
then echo -e '\033[0m\033[1mAbort.'
echo
exit
fi
