#!/data/data/com.termux/files/usr/bin/bash
sleep 0.8

c1='\e[0;1;38;2;0;200;130m'
c2='\e[0;1;77m'

echo -e "${c1}                __.;=====;.__
            _.=+==++=++=+=+===;.
             -=+++=+===+=+=+++++=_
        .     -=:        --==+=++==.
       _vi,                 --+=++++:
      .uvnvi.       _._       -==+==+.
     .vvnvnI     .;==|==;.     :|=||=|.
${c2}+QmQQm${c1}pvvnv; ${c2}_yYsyQQWUUQQQm mQmQM${c1}:${c2}QQQWUV@QQm.
${c2} -QQWQW${c1}pvvo${c2}wZ?.wQQQE${c1}==<${c2}QWWQ/QWQW.QQWW${c1}(: ${c2}jQWQE
${c2}  -@QQQQmmU   jQQQ@${c1}+=<${c2}QWQQ)mQQQ.mQQQC${c1}+;${c2}jWQQ@'
${c2}   -@WQ8Y${c1}nI:   ${c2}QWQQwgQQWV${c1} ${c2}mWQQ.jQWQQgyyWW@!
${c1}     -1vvnvv.      ~+++         ++|+++
      +vnvnnv,                  -|===
       +vnvnvns.           .      :=-
        -Invnvvnsi..___..=sv=.     
          +Invnvnvnnnnnnnnvvnn;.
            ~|Invnvnvvnvvvnnv}+
               -~|{*l}*|~"

echo
echo -n "Are you want to continue installing (Y/N)? "
read input
if [[ $input = "Y" ]] || [[ $input = "y" ]]
then connection="$(ping -c 1 -q www.google.com >&/dev/null; echo $?)"
if [[ "$connection" != 0 ]]
then
echo -e "\033[1;91m          [\033[1;92m-\033[1;91m] No Internet\033[1;92m connection!"
echo
   exit
fi
sleep 1.5
cd $HOME
mkdir void > /dev/null 2>&1
cd void
echo
echo -e '\033[1m\033[38;2;0;80;255m[^_^] Void Installing Starting...'
sleep 1
echo
pkg update -y && pkg install wget curl proot tar -y && wget https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/Installer/Void/void-xfce.sh && chmod +x void-xfce.sh && bash void-xfce.sh
elif [[ $input = "N" ]] || [[ $input = "n" ]]
then echo -e '\033[0m\033[1mAbort.'
echo
exit
fi
